version: '3.5'

services:
  python_cont:
    container_name: db_auth
    ports:
      - "5432:5432"
    environment: 
    - POSTGRES_PASSWORD=password
    - POSTGRES_USER=admin
    image: postgres:14.3-alpine